import argparse as ap

arg = """
Argument of type "tuple[Literal[b"\x00\x00\x11#PaMacCore_GetChannelName"], 
Literal[0], Literal[b"\x00\x00_#PaMacCore_SetupChannelMap"], Literal[0], 
Literal[b"\x00\x00d#PaMacCore_SetupStreamInfo"], Literal[0], Literal[b"\x00\x00##PaWasapi_IsLoopback"], 
Literal[0], Literal[b"\x00\x00A#Pa_AbortStream"], Literal[0], Literal[b"\x00\x00A#Pa_CloseStream"], 
Literal[0], Literal[b"\x00\x00Z#Pa_GetDefaultHostApi"], Literal[0], 
Literal[b"\x00\x00Z#Pa_GetDefaultInputDevice"], Literal[0], Literal[b"\x00\x00Z#Pa_GetDefaultOutputDevice"], 
Literal[0], Literal[b"\x00\x00Z#Pa_GetDeviceCount"], Literal[0], Literal[b"\x00\x00\x00#Pa_GetDeviceInfo"], 
Literal[0], Literal[b"\x00\x00\x0e#Pa_GetErrorText"], Literal[0], Literal[b"\x00\x00Z#Pa_GetHostApiCount"], 
Literal[0], Literal[b"\x00\x00\x03#Pa_GetHostApiInfo"], Literal[0], 
Literal[b"\x00\x00\x09#Pa_GetLastHostErrorInfo"], Literal[0], Literal[b"\x00\x00*#Pa_GetSampleSize"], 
Literal[0], Literal[b"\x00\x00#Pa_GetStreamCpuLoad"], Literal[0], 
Literal[b"\x00\x00\x06#Pa_GetStreamHostApiType"], Literal[0], Literal[b"\x00\x00\x0b#Pa_GetStreamInfo"], 
Literal[0], Literal[b"\x00\x00\#Pa_GetStreamReadAvailable"], Literal[0], 
Literal[b"\x00\x00#Pa_GetStreamTime"], Literal[0], Literal[b"\x00\x00\#Pa_GetStreamWriteAvailable"], 
Literal[0], Literal[b"\x00\x00Z#Pa_GetVersion"], Literal[0], Literal[b"\x00\x00#Pa_GetVersionText"], 
Literal[0], Literal[b"\x00\x00&#Pa_HostApiDeviceIndexToDeviceIndex"], Literal[0], 
Literal[b"\x00\x00#Pa_HostApiTypeIdToHostApiIndex"], Literal[0], Literal[b"\x00\x00Z#Pa_Initialize"], 
Literal[0], Literal[b"\x00\x00#Pa_IsFormatSupported"], Literal[0], Literal[b"\x00\x00A#Pa_IsStreamActive"], 
Literal[0], Literal[b"\x00\x00A#Pa_IsStreamStopped"], Literal[0], Literal[b"\x00\x007#Pa_OpenDefaultStream"], 
Literal[0], Literal[b"\x00\x00-#Pa_OpenStream"], Literal[0], Literal[b"\x00\x00D#Pa_ReadStream"], Literal[0], 
Literal[b"\x00\x00N#Pa_SetStreamFinishedCallback"], Literal[0], Literal[b"\x00\x00h#Pa_Sleep"], Literal[0], 
Literal[b"\x00\x00A#Pa_StartStream"], Literal[0], Literal[b"\x00\x00A#Pa_StopStream"], Literal[0], 
Literal[b"\x00\x00Z#Pa_Terminate"], Literal[0], Literal[b"\x00\x00I#Pa_WriteStream"], Literal[0], 
Literal[b"\xff\xff\xff\x0beAudioCategoryAlerts"], Literal[4], 
Literal[b"\xff\xff\xff\x0beAudioCategoryCommunications"], Literal[3], 
Literal[b"\xff\xff\xff\x0beAudioCategoryGameChat"], Literal[8], 
Literal[b"\xff\xff\xff\x0beAudioCategoryGameEffects"], Literal[6], 
Literal[b"\xff\xff\xff\x0beAudioCategoryGameMedia"], Literal[7], 
Literal[b"\xff\xff\xff\x0beAudioCategoryMedia"], Literal[11], 
Literal[b"\xff\xff\xff\x0beAudioCategoryMovie"], Literal[10],
Literal[b"\xff\xff\xff\x0beAudioCategoryOther"], Literal[0], 
Literal[b"\xff\xff\xff\x0beAudioCategorySoundEffects"], Literal[5], 
Literal[b"\xff\xff\xff\x0beAudioCategorySpeech"], Literal[9], 
Literal[b"\xff\xff\xff\x0beStreamOptionMatchFormat"], Literal[2], 
Literal[b"\xff\xff\xff\x0beStreamOptionNone"], Literal[0], 
Literal[b"\xff\xff\xff\x0beStreamOptionRaw"], Literal[1], 
Literal[b"\xff\xff\xff\x0beThreadPriorityAudio"], Literal[1], 
Literal[b"\xff\xff\xff\x0beThreadPriorityCapture"], Literal[2], 
Literal[b"\xff\xff\xff\x0beThreadPriorityDistribution"], Literal[3], 
Literal[b"\xff\xff\xff\x0beThreadPriorityGames"], Literal[4], Literal[b"\xff\xff\xff\x0beThreadPriorityNone"], 
Literal[0], Literal[b"\xff\xff\xff\x0beThreadPriorityPlayback"], 
Literal[5], Literal[b"\xff\xff\xff\x0beThreadPriorityProAudio"], 
Literal[6], Literal[b"\xff\xff\xff\x0beThreadPriorityWindowManager"], Literal[7], 
Literal[b"\xff\xff\xff\x0bpaAL"], Literal[9], Literal[b"\xff\xff\xff\x0bpaALSA"], 
Literal[8], Literal[b"\xff\xff\xff\x0bpaASIO"], Literal[3], Literal[b"\xff\xff\xff\x0bpaAbort"], 
Literal[2], Literal[b"\xff\xff\xffpaAsioUseChannelSelectors"], Literal[1], 
Literal[b"\xff\xff\xff\x0bpaAudioScienceHPI"], Literal[14], Literal[b"\xff\xff\xff\x0bpaBadBufferPtr"], 
Literal[-9972], Literal[b"\xff\xff\xff\x0bpaBadIODeviceCombination"], Literal[-9993], 
Literal[b"\xff\xff\xff\x0bpaBadStreamPtr"], Literal[-9988], Literal[b"\xff\xff\xff\x0bpaBeOS"], 
Literal[10], Literal[b"\xff\xff\xff\x0bpaBufferTooBig"], Literal[-9991], 
Literal[b"\xff\xff\xff\x0bpaBufferTooSmall"], Literal[-9990], 
Literal[b"\xff\xff\xff\x0bpaCanNotReadFromACallbackStream"], Literal[-9977], 
Literal[b"\xff\xff\xff\x0bpaCanNotReadFromAnOutputOnlyStream"], Literal[-9975], 
Literal[b"\xff\xff\xff\x0bpaCanNotWriteToACallbackStream"], Literal[-9976], 
Literal[b"\xff\xff\xff\x0bpaCanNotWriteToAnInputOnlyStream"], Literal[-9974], 
Literal[b"\xff\xff\xffpaClipOff"], Literal[1], Literal[b"\xff\xff\xff\x0bpaComplete"], 
Literal[1], Literal[b"\xff\xff\xff\x0bpaContinue"], Literal[0], Literal[b"\xff\xff\xff\x0bpaCoreAudio"], 
Literal[5], Literal[b"\xff\xff\xffpaCustomFormat"], Literal[65536], 
Literal[b"\xff\xff\xff\x0bpaDeviceUnavailable"], Literal[-9985], 
Literal[b"\xff\xff\xff\x0bpaDirectSound"], Literal[1], Literal[b"\xff\xff\xffpaDitherOff"], Literal[2], 
Literal[b"\xff\xff\xffpaFloat32"], Literal[1], Literal[b"\xff\xff\xffpaFormatIsSupported"], Literal[0], 
Literal[b"\xff\xff\xffpaFramesPerBufferUnspecified"], Literal[0], 
Literal[b"\xff\xff\xff\x0bpaHostApiNotFound"], Literal[-9979], Literal[b"\xff\xff\xff\x0bpaInDevelopment"], 
Literal[0], Literal[b"\xff\xff\xff\x0bpaIncompatibleHostApiSpecificStreamInfo"], Literal[-9984], 
Literal[b"\xff\xff\xff\x0bpaIncompatibleStreamHostApi"], 
Literal[-9973], Literal[b"\xff\xff\xffpaInputOverflow"], 
Literal[2], Literal[b"\xff\xff\xff\x0bpaInputOverflowed"], Literal[-9981], 
Literal[b"\xff\xff\xffpaInputUnderflow"], Literal[1], Literal[b"\xff\xff\xff\x0bpaInsufficientMemory"], 
Literal[-9992], Literal[b"\xff\xff\xffpaInt16"], Literal[8], Literal[b"\xff\xff\xffpaInt24"], Literal[4], 
Literal[b"\xff\xff\xffpaInt32"], Literal[2], Literal[b"\xff\xff\xffpaInt8"], Literal[16], 
Literal[b"\xff\xff\xff\x0bpaInternalError"], Literal[-9986], Literal[b"\xff\xff\xff\x0bpaInvalidChannelCount"], 
Literal[-9998], Literal[b"\xff\xff\xff\x0bpaInvalidDevice"], Literal[-9996], 
Literal[b"\xff\xff\xff\x0bpaInvalidFlag"], Literal[-9995], Literal[b"\xff\xff\xff\x0bpaInvalidHostApi"], 
Literal[-9978], Literal[b"\xff\xff\xff\x0bpaInvalidSampleRate"], Literal[-9997], 
Literal[b"\xff\xff\xff\x0bpaJACK"], Literal[12], Literal[b"\xff\xff\xff\x0bpaMME"], Literal[2], 
Literal[b"\xff\xff\xffpaMacCoreChangeDeviceParameters"], Literal[1], 
Literal[b"\xff\xff\xffpaMacCoreConversionQualityHigh"], Literal[1024], 
Literal[b"\xff\xff\xffpaMacCoreConversionQualityLow"], Literal[768], 
Literal[b"\xff\xff\xffpaMacCoreConversionQualityMax"], Literal[0], 
Literal[b"\xff\xff\xffpaMacCoreConversionQualityMedium"], Literal[512], 
Literal[b"\xff\xff\xffpaMacCoreConversionQualityMin"], Literal[256], 
Literal[b"\xff\xff\xffpaMacCoreFailIfConversionRequired"], Literal[2], 
Literal[b"\xff\xff\xffpaMacCoreMinimizeCPU"], Literal[257], 
Literal[b"\xff\xff\xffpaMacCoreMinimizeCPUButPlayNice"], Literal[256], 
Literal[b"\xff\xff\xffpaMacCorePlayNice"], Literal[0], Literal[b"\xff\xff\xffpaMacCorePro"], Literal[1], 
Literal[b"\xff\xff\xffpaNeverDropInput"], Literal[4], Literal[b"\xff\xff\xffpaNoDevice"], Literal[-1], 
Literal[b"\xff\xff\xff\x0bpaNoError"], Literal[0], Literal[b"\xff\xff\xffpaNoFlag"], Literal[0], 
Literal[b"\xff\xff\xffpaNonInterleaved"], Literal[2147483648], Literal[b"\xff\xff\xff\x0bpaNotInitialized"], 
Literal[-10000], Literal[b"\xff\xff\xff\x0bpaNullCallback"], Literal[-9989], Literal[b"\xff\xff\xff\x0bpaOSS"], 
Literal[7], Literal[b"\xff\xff\xffpaOutputOverflow"], Literal[8], Literal[b"\xff\xff\xffpaOutputUnderflow"], 
Literal[4], Literal[b"\xff\xff\xff\x0bpaOutputUnderflowed"], Literal[-9980], 
Literal[b"\xff\xff\xffpaPlatformSpecificFlags"], Literal[4294901760], 
Literal[b"\xff\xff\xffpaPrimeOutputBuffersUsingStreamCallback"], Literal[8], 
Literal[b"\xff\xff\xffpaPrimingOutput"], Literal[16], Literal[b"\xff\xff\xff\x0bpaSampleFormatNotSupported"], 
Literal[-9994], Literal[b"\xff\xff\xff\x0bpaSoundManager"], Literal[4], 
Literal[b"\xff\xff\xff\x0bpaStreamIsNotStopped"], Literal[-9982], Literal[b"\xff\xff\xff\x0bpaStreamIsStopped"], 
Literal[-9983], Literal[b"\xff\xff\xff\x0bpaTimedOut"], Literal[-9987], Literal[b"\xff\xff\xffpaUInt8"], 
Literal[32], Literal[b"\xff\xff\xff\x0bpaUnanticipatedHostError"], Literal[-9999], 
Literal[b"\xff\xff\xffpaUseHostApiSpecificDeviceSpecification"], Literal[-2], 
Literal[b"\xff\xff\xff\x0bpaWASAPI"], Literal[13], Literal[b"\xff\xff\xff\x0bpaWDMKS"], Literal[11], 
Literal[b"\xff\xff\xff\x0bpaWinWasapiExclusive"], Literal[1], Literal[b"\xff\xff\xff\x0bpaWinWasapiPolling"], 
Literal[8], Literal[b"\xff\xff\xff\x0bpaWinWasapiRedirectHostProcessor"], Literal[2], 
Literal[b"\xff\xff\xff\x0bpaWinWasapiThreadPriority"], Literal[16], 
Literal[b"\xff\xff\xff\x0bpaWinWasapiUseChannelMask"], Literal[4]]
" cannot be assigned to parameter "_globals" of type "tuple[str | int, ...]" in function "__init__" ?
"""


def main(a):
    p = ap.ArgumentParser()
    r = p.parse_args(a)
    return r if type(r) == str else TypeError("Value `r` is not type str.")


m = main(arg)
print(m)
